Feature/mood microservice
Team-07-Looney/looney-general pull request #77
Opened 2023-12-06 13:31 UTC by DanielBartha

Jessica Dinova included (broken down laptop, pair programming)

2023-12-08 11:12 UTC, v-stamenova requested changes
Mostly the naming convention in singular form

Either unit testing (which yes please) or establish routes so that we can manually test

2023-12-08 11:12 UTC, v-stamenova commented on backend/moods/code/controllers/moodTypesController.js
Naming convention in singular form - example `createMoodType`, `getAllMoodTypes`, `getMoodTypeInstanceById`

2023-12-08 11:12 UTC, v-stamenova commented on backend/moods/code/controllers/moodsController.js
Naming convention in singular form

2023-12-08 11:12 UTC, v-stamenova commented on backend/moods/code/controllers/reasonsController.js
Naming convention in singular form

2023-12-08 11:12 UTC, v-stamenova commented on backend/moods/code/controllers/recordsController.js
Naming convention in singular form

2023-12-11 07:56 UTC, v-stamenova commented on .github/workflows/backend.yml
I am definitely not sure about this. I need to look into it in more detail and will talk in person.

2023-12-11 14:15 UTC, JessicaDinova commented on backend/moods/code/controllers/moodTypesController.js
done

2023-12-11 14:15 UTC, JessicaDinova commented on backend/moods/code/controllers/moodsController.js
done

2023-12-11 14:15 UTC, JessicaDinova commented on backend/moods/code/controllers/reasonsController.js
done

2023-12-11 14:15 UTC, JessicaDinova commented on backend/moods/code/controllers/recordsController.js
done

2023-12-11 14:20 UTC, v-stamenova approved these changes

2023-12-12 12:40 UTC, merged